Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"

  config.vm.network "private_network", ip: "192.168.50.4"

  config.vm.hostname = "ezconf.tp1.efrei"

  config.vm.define "ezconf.tp1.efrei"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.disksize.size = '20GB'
end
