Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"

  config.vm.network "private_network", ip: "10.3.1.22"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 1
    vb.customize ['modifyvm', :id, '--nested-hw-virt', 'on']
  end
end
