Vagrant.configure("2") do |config| 
  config.vm.define "node1" do |node1|
    node1.vm.box = "generic/rocky9"
    node1.vm.network "private_network", ip: "10.1.1.101"
    node1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "generic/rocky9" 
    node2.vm.network "private_network", ip: "10.1.1.102"
    node2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
    end
  end
end
